[project]
name = "finance-ca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "alembic>=1.17.2",
    "fastapi>=0.123.5",
    "httpx>=0.28.1",
    "sqlalchemy>=2.0.44",
]
